# Numpy Basics - Lecture

### Workshop 19.03.2019

## Using NumPy

Once you have installed NumPy you can import it as a library.

In [1]:
import numpy as np

## Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d. NumPy arrays is the work horse of the NumPy library.

### Convert from Python List

In [2]:
my_list = [1,2,3,4,5]

print(my_list)

[1, 2, 3, 4, 5]


In [3]:
my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5])

#### 2D list to matrix array

In [4]:
my_matrix=[[1,2,3],
          [4,5,6],
          [7,8,9]]

print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
matrix_array = np.array(my_matrix)
print(matrix_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


___

<h3 align="center">Built-in methods </h3> 

### arange( )

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### zeros ( )

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones ( )

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones (  (4,4)  )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace ( )

In [12]:
# np.linspace (start, stop, number_of_points)
np.linspace(0,1,101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

___

<h3 align="center">Operations with arrays</h3> 

### + , - , / , * & ** all work

In [13]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [14]:
x+x

array([0, 2, 4, 6, 8])

In [15]:
x-x 

array([0, 0, 0, 0, 0])

In [16]:
x*x

array([ 0,  1,  4,  9, 16])

In [17]:
x/x

C:\Users\christoffer.wibe.due\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.])

___

<h3 align="center">array methods</h3> 

### max ( ), min ( ), mean( ) & sum ( )

In [18]:
x.max()

4

In [19]:
x.min()

0

In [20]:
x.mean()

2.0

In [21]:
x.sum()

10

### argmax( ), argmin ( )
Find the index of the max and min value

In [22]:
z = np.array([45,22,11,99,78])

In [23]:
z.argmax()

3

In [24]:
#print out the largest number
print(z[3])

99


In [25]:
z.argmin()

2

In [26]:
#Prints out the smalest number
print(z[2])

11


___

<h3 align="center">Shape, reshape and dtypes</h3> 

### shape
Shape is an attribute that arrays have (not a method):

In [27]:
z.shape

(5,)

In [28]:
matrix_array.shape

(3, 3)

### reshape ( )

In [29]:
np.arange(100).reshape((10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### dtypes

In [30]:
z.dtype

dtype('int32')

<h3 align="center">Indexing</h3> 

### Bracket indexing and selection

In [31]:
big_10_by_10 = np.arange(100).reshape((10,10))

print(big_10_by_10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


Grab the 11:

In [32]:
#Alterantive 1
big_10_by_10[1][1]

11

In [33]:
#Alterantive 2
big_10_by_10[1,1]

11

##### Grab [54,55]

In [34]:
# Alterantive 1
big_10_by_10[5][4:6]

array([54, 55])

In [35]:
#Alterantive 2
big_10_by_10[5,4:6]

array([54, 55])

#### Grab
[ [85,86] , 

[95,96] ]

In [36]:

big_10_by_10[8:,5:7]

array([[85, 86],
       [95, 96]])

### Broadcasting

In [37]:
arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [38]:
slice_of_arr = arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [39]:
slice_of_arr[:] = 42
print(slice_of_arr)

[42 42 42 42 42 42]


In [43]:
arr

array([42, 42, 42, 42, 42, 42,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Kan ta kopi:

In [42]:
arr_copy = arr.copy()

___

# Well done!